apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-sodtyefo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-sodtyefo:eca0cab6f4f952ccc52a36c3dd0bd19176bcab87@sha256:1e4a0c76943b8f8f8de5e8af33015781a93d578df4bda1619f8a24758c508d61
        name: container-image  
